"""AI-consumable Markdown reconnaissance report.

The output of this writer is meant to be copy/pasted directly into an AI
assistant (ChatGPT / Claude / Gemini) for next-step guidance. Therefore:
  * sections appear in a stable order
  * data is presented as tables / tight bullet lists (no raw JSON dumps)
  * no actual secret values are leaked — only the fact that something was
    flagged
  * a clear "How to use this report" block sits near the top so a human
    sees it before sending it to an AI
"""
from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, Iterable, List, Optional


TOOL_VERSION = "2.0.0"
TOOL_NAME    = "HunterPy"


# --------------------------------------------------------------------------
def render_markdown(target: str,
                    metadata: Dict[str, Any],
                    findings: List[Dict[str, Any]],
                    recon: Optional[Dict[str, Any]] = None,
                    surface: Optional[Dict[str, Any]] = None,
                    javascript: Optional[Dict[str, Any]] = None,
                    dns_records: Optional[Dict[str, Any]] = None,
                    whois_data: Optional[Dict[str, Any]] = None,
                    cookies: Optional[List[Dict[str, Any]]] = None,
                    dorks: Optional[Dict[str, Any]] = None) -> str:
    """Return a Markdown string. All callers should use this single function."""
    recon      = recon or {}
    surface    = surface or {}
    javascript = javascript or {}
    dns_records = dns_records or {}
    whois_data = whois_data or {}
    cookies = cookies or []

    summary = build_findings_summary(findings, surface, javascript, cookies)

    parts: List[str] = []
    # YAML frontmatter — machine-readable summary for LLM ingestion + CI
    # pipelines. Humans skip it; LLMs love it. Schema is documented in
    # the README "Reports" section.
    parts.append(_yaml_frontmatter(target, metadata, findings))
    parts.append(_h1(f"Reconnaissance Report — {target}"))
    parts.append(f"_Generated by {TOOL_NAME} v{TOOL_VERSION} on "
                 f"{metadata.get('end_time') or datetime.utcnow().isoformat() + 'Z'}_\n")

    # --- legal + instructions front-and-center ---------------------------
    parts.append(_h2("Legal Notice"))
    parts.append("> This report was produced by an authorized security "
                 "assessment. Do not use it against systems you do not own "
                 "or do not have explicit written permission to test.\n")

    parts.append(_h2("How To Use This Report"))
    parts.append(
        "Copy the **entire contents of this Markdown file** and paste it into "
        "an AI assistant such as ChatGPT, Claude, or Gemini. Ask it to:\n"
        "\n"
        "1. Analyze the findings below and rank them by exploitability.\n"
        "2. Suggest specific vulnerability classes worth investigating based "
        "on the detected technology stack and exposed surface.\n"
        "3. Recommend the next manual tests to perform (no automated attacks).\n"
        "4. Highlight any findings that suggest a chained / multi-step attack.\n"
        "\n"
        "This tool performs **passive reconnaissance only** — no attack "
        "payloads were sent. The AI's role is strategic guidance, not "
        "exploitation.\n"
    )

    # --- scan metadata ---------------------------------------------------
    parts.append(_h2("Scan Metadata"))
    parts.append(_kv_table([
        ("Target",      target),
        ("Mode",        metadata.get("mode", "n/a")),
        ("Scan ID",     metadata.get("scan_id", "n/a")),
        ("Start time",  metadata.get("start_time", "n/a")),
        ("End time",    metadata.get("end_time", "n/a")),
        ("Duration",    metadata.get("duration", "n/a")),
        ("Modules run", ", ".join(metadata.get("modules_run", []) or [])),
    ]))

    # --- tech ------------------------------------------------------------
    parts.append(_h2("Technology Stack"))
    parts.append(_render_tech(findings, recon))

    # --- headers ---------------------------------------------------------
    parts.append(_h2("Security Header Audit"))
    parts.append(_render_header_audit(findings, recon))

    # --- cookies ---------------------------------------------------------
    parts.append(_h2("Cookie Security"))
    parts.append(_render_cookies(cookies))

    # --- DNS -------------------------------------------------------------
    parts.append(_h2("DNS Records"))
    parts.append(_render_dns(dns_records))

    # --- WHOIS -----------------------------------------------------------
    parts.append(_h2("WHOIS Information"))
    parts.append(_render_whois(whois_data))

    # --- discovered links ------------------------------------------------
    parts.append(_h2("Discovered Links"))
    parts.append(_render_links(surface))

    # --- forms -----------------------------------------------------------
    parts.append(_h2("Forms Discovered"))
    parts.append(_render_forms(surface.get("forms", [])))

    # --- URL params ------------------------------------------------------
    parts.append(_h2("URL Parameters Found"))
    parts.append(_render_params(surface.get("url_params", [])))

    # --- sensitive paths -------------------------------------------------
    parts.append(_h2("Sensitive Path Check"))
    parts.append(_render_path_check(surface.get("sensitive_paths", [])))

    # --- JS analysis -----------------------------------------------------
    parts.append(_h2("JavaScript Analysis"))
    parts.append(_render_javascript(javascript))

    # --- Google dorks ----------------------------------------------------
    parts.append(_h2("Google Dorks (for manual review)"))
    parts.append(_render_dorks(dorks or {}))

    # --- verification results -------------------------------------------
    verified = [f for f in findings if f.get("verification")]
    if verified:
        parts.append(_h2("Verification Results (Phase 6 — safe probes)"))
        parts.append(_render_verifications(verified))

    # --- summary + next steps -------------------------------------------
    parts.append(_h2("Summary of Notable Findings"))
    if summary:
        for s in summary:
            parts.append(f"- {s}")
        parts.append("")
    else:
        parts.append("_No notable findings flagged._\n")

    parts.append(_h2("Next Steps"))
    parts.append(
        "This report was designed to be pasted into an AI assistant for "
        "further analysis. After pasting, prompt the AI for: (a) the most "
        "promising vulnerability classes to investigate given the technology "
        "stack and exposed surface, (b) specific manual tests to run against "
        "the discovered endpoints and forms, (c) which areas of the "
        "application are most likely to contain security weaknesses, and (d) "
        "any chained / multi-step attacks suggested by the combination of "
        "findings. **No automated exploitation should be performed — use the "
        "AI's suggestions to guide manual, authorized testing only.**\n"
    )
    return "\n".join(parts)


# ==========================================================================
# helpers
# ==========================================================================
def build_findings_summary(findings: List[Dict[str, Any]],
                           surface: Dict[str, Any],
                           javascript: Dict[str, Any],
                           cookies: List[Dict[str, Any]]) -> List[str]:
    """Short list of plain-English bullets — the part an AI grabs first."""
    out: List[str] = []

    interesting = [f for f in findings if f.get("classification") == "INTERESTING"]
    if interesting:
        out.append(f"{len(interesting)} INTERESTING finding(s) — investigate first.")

    missing = [f["title"] for f in findings
               if f.get("type") == "missing_security_header"]
    if missing:
        out.append("Missing security headers: "
                   + ", ".join(sorted({m.split(': ', 1)[-1] for m in missing})) + ".")

    weak_csp = [f for f in findings if f.get("type") == "weak_csp"]
    if weak_csp:
        out.append(f"Content-Security-Policy contains weak directives "
                   f"({len(weak_csp)} issue(s)).")

    ssl_issues = [f for f in findings if f.get("module") == "ssl"
                  and f.get("classification") in ("INTERESTING", "COMMON")]
    if ssl_issues:
        out.append(f"{len(ssl_issues)} TLS/cert finding(s) reported.")

    path_hits = [p for p in surface.get("sensitive_paths", [])
                 if p.get("status_code") and 200 <= p["status_code"] < 300
                 and p.get("has_content")]
    if path_hits:
        out.append("Sensitive paths reachable with non-empty body: "
                   + ", ".join(p["url"].rsplit("/", 1)[-1] or p["url"]
                               for p in path_hits) + ".")

    if javascript.get("sensitive_keyword_hits"):
        out.append(f"{len(javascript['sensitive_keyword_hits'])} sensitive "
                   "keyword occurrence(s) flagged in JavaScript files "
                   "(values not logged).")

    if javascript.get("endpoints"):
        out.append(f"{len(javascript['endpoints'])} API/GraphQL endpoint(s) "
                   "referenced in JavaScript source.")

    if surface.get("forms"):
        login_forms = [f for f in surface["forms"]
                       if any(i.get("type") == "password" for i in f.get("fields", []))]
        if login_forms:
            out.append(f"{len(login_forms)} login form(s) discovered.")

    cookie_issues = []
    for c in cookies:
        flags = []
        if not c.get("httponly"): flags.append("HttpOnly")
        if not c.get("secure"):   flags.append("Secure")
        if not c.get("samesite"): flags.append("SameSite")
        if flags:
            cookie_issues.append(f"{c.get('name', '?')} missing {'+'.join(flags)}")
    if cookie_issues:
        out.append("Cookies missing security flags: "
                   + "; ".join(cookie_issues[:6]) + ".")

    cves = [f for f in findings if f.get("type") == "cve"]
    if cves:
        top = sorted(cves, key=lambda x: -float(x.get("cvss") or 0))[:3]
        out.append("Possible CVEs based on disclosed software version: "
                   + ", ".join(
                       f"{c['evidence'].get('cve_id', '?')} (CVSS "
                       f"{c.get('cvss', '?')})" for c in top) + ".")
    return out


def parse_cookies_from_findings(findings: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """Cookies aren't a first-class module result — derive them from headers."""
    return []  # left as a hook; orchestrator passes cookies explicitly


# ---- section renderers ---------------------------------------------------
def _render_tech(findings, recon) -> str:
    techs = recon.get("technologies", []) if isinstance(recon, dict) else []
    fp = next((f for f in findings if f.get("type") == "tech_fingerprint"), None)
    rows = []
    if fp and fp.get("tech"):
        for k, v in fp["tech"].items():
            rows.append((k, v))
    for t in techs:
        rows.append(("detected", t))
    if not rows:
        return "_No technology fingerprint available._\n"
    return _kv_table(rows)


def _render_header_audit(findings, recon) -> str:
    headers = (recon or {}).get("headers", {})
    expected = [
        ("Content-Security-Policy", "content-security-policy"),
        ("Strict-Transport-Security", "strict-transport-security"),
        ("X-Frame-Options", "x-frame-options"),
        ("X-Content-Type-Options", "x-content-type-options"),
        ("Referrer-Policy", "referrer-policy"),
        ("Permissions-Policy", "permissions-policy"),
        ("X-XSS-Protection", "x-xss-protection"),
    ]
    rows = [["Header", "Present", "Value / Notes"]]
    for label, key in expected:
        present = key in headers
        value = headers.get(key, "")
        note = ""
        if present:
            if key == "content-security-policy":
                bad = []
                if "unsafe-inline" in value: bad.append("unsafe-inline")
                if "unsafe-eval"   in value: bad.append("unsafe-eval")
                note = f"weak directives: {', '.join(bad)}" if bad else "present"
            elif key == "strict-transport-security":
                note = "includeSubDomains" if "includesubdomains" in value.lower() \
                       else "no includeSubDomains"
            elif key == "x-frame-options":
                note = "ok" if value.upper() in ("DENY", "SAMEORIGIN") else "non-standard"
            elif key == "x-content-type-options":
                note = "ok" if value.lower() == "nosniff" else "non-standard"
            elif key == "x-xss-protection":
                note = "header is deprecated"
            else:
                note = "recorded as-is"
        else:
            note = "missing"
        rows.append([label, "yes" if present else "no", f"{value[:80]} ({note})" if present else "—"])
    return _md_table(rows)


def _render_cookies(cookies) -> str:
    if not cookies:
        return "_No Set-Cookie headers observed on the landing page._\n"
    rows = [["Name", "HttpOnly", "Secure", "SameSite", "Notes"]]
    for c in cookies:
        notes = []
        if not c.get("httponly"): notes.append("missing HttpOnly")
        if not c.get("secure"):   notes.append("missing Secure")
        if not c.get("samesite"): notes.append("missing SameSite")
        rows.append([
            c.get("name", "?"),
            "yes" if c.get("httponly") else "no",
            "yes" if c.get("secure") else "no",
            c.get("samesite") or "—",
            "; ".join(notes) or "ok",
        ])
    return _md_table(rows)


def _render_dns(dns_records) -> str:
    if not dns_records:
        return "_DNS module did not run or returned no data._\n"
    out = []
    if dns_records.get("a"):
        out.append("**A records**")
        for ip in dns_records["a"]:
            out.append(f"- {ip}")
        out.append("")
    if dns_records.get("mx"):
        out.append("**MX records**")
        for mx in dns_records["mx"]:
            out.append(f"- {mx['priority']:>3}  {mx['mail_server']}")
        out.append("")
    if dns_records.get("ns"):
        out.append("**NS records**")
        for ns in dns_records["ns"]:
            out.append(f"- {ns}")
        out.append("")
    if dns_records.get("txt"):
        out.append("**TXT records**")
        for txt in dns_records["txt"]:
            safe = txt.replace("|", "\\|")[:200]
            out.append(f"- `{safe}`")
        out.append("")
    if dns_records.get("cname"):
        out.append(f"**CNAME:** {dns_records['cname']}\n")
    return "\n".join(out) or "_No DNS records resolved._\n"


def _render_whois(whois_data) -> str:
    if not whois_data:
        return "_WHOIS module did not run or no data returned._\n"
    rows = []
    for k, v in whois_data.items():
        if v is None:
            continue
        if isinstance(v, list):
            v = ", ".join(str(x) for x in v)
        rows.append((k, str(v)))
    return _kv_table(rows) if rows else "_No usable WHOIS fields returned._\n"


def _render_links(surface) -> str:
    internal = surface.get("internal_links", [])
    external = surface.get("external_links", [])
    subdomains = surface.get("subdomains", [])
    parts = [
        f"- Internal links: **{len(internal)}**",
        f"- External links: **{len(external)}**",
        f"- Subdomains referenced in source: **{len(subdomains)}**",
        "",
    ]
    if internal:
        parts.append("**Internal links (first 25):**")
        for u in internal[:25]:
            parts.append(f"- {u}")
        parts.append("")
    if subdomains:
        parts.append("**Subdomains in source:**")
        for s in subdomains:
            parts.append(f"- {s}")
        parts.append("")
    return "\n".join(parts)


def _render_forms(forms) -> str:
    if not forms:
        return "_No forms found on the landing page._\n"
    out: List[str] = []
    for i, f in enumerate(forms, 1):
        out.append(f"**Form {i}** — `{f.get('method', 'GET')}` "
                   f"→ {f.get('action') or '(self)'}")
        for inp in f.get("fields", []):
            tag = inp.get("type", "text")
            mark = " *(hidden)*" if inp.get("hidden") else ""
            out.append(f"  - `{inp.get('name') or '?'}` [{tag}]{mark}")
        out.append("")
    return "\n".join(out)


def _render_params(params) -> str:
    if not params:
        return "_No URL parameters found in discovered links._\n"
    return ", ".join(f"`{p}`" for p in params) + "\n"


def _render_path_check(paths) -> str:
    if not paths:
        return "_No sensitive path check performed._\n"
    rows = [["Path", "Status", "Body present"]]
    for p in paths:
        rows.append([
            p.get("url", "?"),
            str(p.get("status_code") if p.get("status_code") is not None else "—"),
            "yes" if p.get("has_content") else "no",
        ])
    return _md_table(rows)


def _render_dorks(dorks: Dict[str, Any]) -> str:
    items = dorks.get("dorks") if isinstance(dorks, dict) else None
    if not items:
        return ("_No dork suggestions generated. Enable the `dorks` module "
                "or run `--list-dork-templates` to see what's available._\n")
    # group by template
    by_tpl: Dict[str, list] = {}
    for d in items:
        by_tpl.setdefault(d.get("template", "?"), []).append(d)
    out: List[str] = [
        "_Open these in Google to manually review. HunterPy does **not** scrape "
        "Google by default (ToS + CAPTCHA). To actually fetch results, see "
        "`--dorks-active`._\n"
    ]
    for tpl, ds in by_tpl.items():
        sev = ds[0].get("severity", "info").upper()
        desc = ds[0].get("description", "")
        out.append(f"### `{tpl}` — {sev}")
        out.append(f"_{desc}_\n")
        for d in ds[:8]:
            q = d.get("query", "").replace("|", "\\|")
            u = d.get("google_url", "")
            out.append(f"- [`{q}`]({u})")
        if len(ds) > 8:
            out.append(f"- _… and {len(ds) - 8} more dorks in this template_")
        out.append("")
    return "\n".join(out)


def _render_javascript(js) -> str:
    if not js:
        return "_JS analyzer did not run._\n"
    out: List[str] = []
    first = js.get("first_party_scripts", [])
    third = js.get("third_party_scripts", [])
    hits  = js.get("sensitive_keyword_hits", [])
    eps   = js.get("endpoints", [])

    out.append(f"- First-party scripts: **{len(first)}**")
    out.append(f"- Third-party scripts: **{len(third)}**")
    out.append("")

    if first:
        out.append("**First-party scripts:**")
        for u in first[:20]:
            out.append(f"- {u}")
        out.append("")

    if hits:
        out.append("**Sensitive keyword occurrences (values not logged):**")
        out.append("")
        out.append("| File | Line | Keyword | Context (masked) |")
        out.append("|------|-----:|---------|------------------|")
        for h in hits[:50]:
            file_short = h.get("file", "?").split("/")[-1] or h.get("file")
            ctx = h.get("context", "").replace("|", "\\|")[:120]
            out.append(f"| `{file_short}` | {h.get('line')} | "
                       f"`{h.get('keyword')}` | `{ctx}` |")
        out.append("")

    if eps:
        out.append("**Endpoints referenced in JS:**")
        for e in eps[:50]:
            out.append(f"- `{e}`")
        out.append("")

    return "\n".join(out) or "_Nothing detected._\n"


# ---- generic markdown primitives ----------------------------------------
def _render_verifications(findings: List[Dict[str, Any]]) -> str:
    """Render the verification table.

    The table is intentionally short — full evidence (request/response
    bodies, hashed-out secrets) lives in
    ``<output>/verification/<finding_uid>/``. The report shows only the
    *outcome*, not the captured bytes.
    """
    rows = [["#", "Finding type", "Probe", "Safety", "Status", "Proof"]]
    status_glyph = {
        "confirmed":    "✅ confirmed",
        "inconclusive": "⚠️ inconclusive",
        "safe_failed":  "🚫 failed",
        "skipped":      "⏭️ skipped",
        "error":        "❌ error",
    }
    for i, f in enumerate(findings, start=1):
        v = f.get("verification") or {}
        rows.append([
            str(i),
            f.get("type", "?"),
            v.get("probe_name", "?"),
            str(v.get("safety_level", "?")),
            status_glyph.get(str(v.get("status", "")).lower(),
                              str(v.get("status", ""))),
            _esc((v.get("proof") or v.get("summary") or "")[:80]),
        ])
    return (
        _md_table(rows) +
        "\n_Full evidence bundles (every request/response, with secrets "
        "redacted to SHA-256 fingerprints) are under "
        "`<output>/verification/<finding_uid>/`._\n"
    )


def _yaml_frontmatter(target: str, metadata: Dict[str, Any],
                       findings: List[Dict[str, Any]]) -> str:
    """Render a YAML frontmatter block at the top of the markdown report.

    LLMs (ChatGPT, Claude, Gemini) parse this cleanly. CI pipelines can
    grep it for a summary count without parsing the whole report.

    Schema:
      scan_id, target, mode, generated_at
      findings_summary: {total, critical, high, medium, low, info, by_class}
      attack_chains: list of {type, severity, steps}
      verification_summary: {confirmed, inconclusive, skipped, total}

    Hand-rolled to avoid a PyYAML dependency for one block of fixed shape.
    """
    sev_counts: Dict[str, int] = {}
    cls_counts: Dict[str, int] = {}
    for f in findings:
        sev = (f.get("severity") or "UNKNOWN").upper()
        sev_counts[sev] = sev_counts.get(sev, 0) + 1
        cls = f.get("classification") or "UNCLASSIFIED"
        cls_counts[cls] = cls_counts.get(cls, 0) + 1

    chains = [f for f in findings if f.get("type", "").startswith("chain_")]
    verifs = [f for f in findings if f.get("verification")]
    v_status: Dict[str, int] = {}
    for v in verifs:
        st = (v.get("verification") or {}).get("status", "unknown")
        v_status[st] = v_status.get(st, 0) + 1

    lines: List[str] = ["---"]
    lines.append(f"scan_id: {_yq(metadata.get('scan_id', 'unknown'))}")
    lines.append(f"target: {_yq(target)}")
    lines.append(f"mode: {_yq(metadata.get('mode', 'n/a'))}")
    lines.append(f"generated_at: {_yq(metadata.get('end_time') or datetime.utcnow().isoformat() + 'Z')}")
    lines.append(f"tool: {_yq(TOOL_NAME)}")
    lines.append(f"tool_version: {_yq(TOOL_VERSION)}")

    lines.append("findings_summary:")
    lines.append(f"  total: {len(findings)}")
    for sev in ("CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO", "UNKNOWN"):
        if sev_counts.get(sev):
            lines.append(f"  {sev.lower()}: {sev_counts[sev]}")
    if cls_counts:
        lines.append("  by_class:")
        for cls, n in sorted(cls_counts.items()):
            lines.append(f"    {cls.lower()}: {n}")

    if chains:
        lines.append("attack_chains:")
        for c in chains:
            lines.append(f"  - type: {_yq(c.get('type', ''))}")
            lines.append(f"    severity: {_yq((c.get('severity') or '').upper())}")
            steps = c.get("steps") or c.get("components") or []
            if steps:
                lines.append("    steps:")
                for s in steps:
                    lines.append(f"      - {_yq(str(s))}")

    if verifs:
        lines.append("verification_summary:")
        lines.append(f"  total: {len(verifs)}")
        for status, n in sorted(v_status.items()):
            lines.append(f"  {status}: {n}")

    lines.append("---\n")
    return "\n".join(lines)


def _yq(s: Any) -> str:
    """Quote a string for YAML emission. Safe for the small set of values
    we put in the frontmatter (no nested structures, no multiline)."""
    if s is None:
        return "null"
    txt = str(s)
    # Conservative: always single-quote, doubling embedded single-quotes.
    return "'" + txt.replace("'", "''") + "'"


def _h1(text: str) -> str: return f"# {text}\n"
def _h2(text: str) -> str: return f"\n## {text}\n"


def _kv_table(pairs: Iterable) -> str:
    rows = [["Key", "Value"]]
    for k, v in pairs:
        rows.append([str(k), str(v).replace("\n", " ")])
    return _md_table(rows)


def _md_table(rows: List[List[str]]) -> str:
    if not rows:
        return ""
    header, *body = rows
    out = ["| " + " | ".join(_esc(c) for c in header) + " |",
           "|" + "|".join(["---"] * len(header)) + "|"]
    for r in body:
        cells = [_esc(c) for c in r]
        # pad short rows
        while len(cells) < len(header):
            cells.append("")
        out.append("| " + " | ".join(cells) + " |")
    return "\n".join(out) + "\n"


def _esc(cell) -> str:
    return str(cell).replace("|", "\\|").replace("\n", " ")
